# Generated code do not commit.
file(TO_CMAKE_PATH "D:\\Caio\\FlutterSA3\\sa3\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "D:\\Caio\\TESTE" PROJECT_DIR)

set(FLUTTER_VERSION "0.1.0" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 0 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=D:\\Caio\\FlutterSA3\\sa3\\flutter"
  "PROJECT_DIR=D:\\Caio\\TESTE"
  "FLUTTER_ROOT=D:\\Caio\\FlutterSA3\\sa3\\flutter"
  "FLUTTER_EPHEMERAL_DIR=D:\\Caio\\TESTE\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=D:\\Caio\\TESTE"
  "FLUTTER_TARGET=D:\\Caio\\TESTE\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9lNzZjOTU2NDk4ODQxZTFhYjQ1ODU3N2QzODkyMDAzZTU1M2U0ZjNjLw=="
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=D:\\Caio\\TESTE\\.dart_tool\\package_config.json"
)
